swagger: '2.0'
info:
  description: Specificatie StUF Json opvragen MAC
  version: LO GBA 3.10
  title: RaadpleegMaatschappelijkeActiviteitOpKvKnummer
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /RaadpleegMaatschappelijkeActiviteitOpKvKnummer:
    get:
      summary: ''
      description: ''
      consumes: []
      produces:
        - application/json
      parameters:
        - name: zenderOrganisatie
          in: header
          description: 'Organisatiecode van de opvragende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: zenderApplicatie
          in: header
          description: 'Applicatiecode van de opvragende organisatie'
          required: false
          type: string
        - name: zenderGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: zenderAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens opvraagt'
          required: false
          type: string          
        - name: ontvangerOrganisatie
          in: header
          description: 'Organisatiecode van de leverende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: ontvangerApplicatie
          in: header
          description: 'Applicatiecode van de leverende organisatie'
          required: false
          type: string
        - name: ontvangerGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: ontvangerAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens levert'
          required: false
          type: string        
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/MaatschappelijkeActiviteiten'
    parameters:
        - name: kvknummer
          in: query
          required: true
          type: string
definitions:
  MaatschappelijkeActiviteiten:
    type: object
    properties:
      kvkNummer:
        type: string
        description: ''
      handelsnamen:
        type: array
        description: ''
        items:
          type: object
          properties:
            handelsnaam:
              type: string
              description: ''
            verkorteNaam:
              type: string
              description: ''
      activiteiten:
        type: array
        description: ''
        items:
          type: object
          properties:
            activiteitcode:
              type: integer
              description: ''
            activiteit:
              type: string
              description: ''
            indicatieHoofdactiviteit:
              type: string
              description: ''
      heeftAlsEigenaar:
        type: array
        description: ''
        items:
          type: object
          properties:
            periodeGeldigheid.van:
              format: date-time
              type: string
              description: ''
            periodeGeldigheid.totEnMet:
              format: date-time
              type: string
              description: ''
            eigenaar:
              type: string
              description: ''    
      IngeschrevenNietNatuurlijkPersoon:
        type: object
        properties:
              statutaireNaam:
                type: string
                description: ''
              datumAanvang:
                format: date-time
                type: string
                description: ''
              datumBeeinding:
                format: date-time
                type: string
                description: ''
              rsin:
                type: string
                description: ''
              rechtsvorm:
                type: string
                description: ''
              datumVoortzetting:
                format: date-time
                type: string
                description: ''
      bezoekAdres:
        type: object
        properties:
          periodeGeldigheid:
            type: object
            properties:
              van:
                format: date-time
                type: string
              totEnMet:
                format: date-time
                type: string
          adres:
            type: object
            properties:
              identificatieNummeraanduiding:
                type: string
              postcode:
                type: string          
              huisnummer:
                type: integer
              huisletter:
                type: string   
              huisnummertoevoeging:
                type: string
              locatiebeschrijving:
                type: string          
              openbareruimtenaam:
                type: string
              woonplaatsNaam:
                type: string    
              woonplaatsIdentificatieCode:
                type: string                  
      AnderBuitenlandsNietNatuurlijkPersoon:                
        type: object
        properties:
              statutaireNaam:
                type: string
                description: ''
              datumAanvang:
                format: date-time
                type: string
                description: ''
              datumBeeinding:
                format: date-time
                type: string
                description: ''
      IngeschrevenPersoon:                
        type: object
        properties:
              voorlettersAanschrijving:
                type: string
                description: ''
              voornamen:
                type: string
                description: ''
              voorvoegselGeslachtsnaam:
                type: string
                description: ''                        
              geslachtsnaam:
                type: string
                description: ''
              geslachtsaanduiding:
                type: string
                description: ''
              aanschrijfwijze:
                type: string
                description: ''
              geboortedatum:
                type: string
                description: ''                   
      verblijfsadres:
        type: object
        properties:
          periodeGeldigheid:
            type: object
            properties:
              van:
                format: date-time
                type: string
              totEnMet:
                format: date-time
                type: string
          adres:
            type: object
            properties:
              identificatieNummeraanduiding:
                type: string
              postcode:
                type: string          
              huisnummer:
                type: string
              huisletter:
                type: string   
              huisnummertoevoeging:
                type: string
              locatiebeschrijving:
                type: string          
              openbareruimtenaam:
                type: string
              woonplaatsNaam:
                type: string    
              woonplaatsIdentificatie:
                type: string                          
      Adresbuitenland:
        type: object
        properties:
          landcode:
            type: object
            properties:
              landnaam:
                type: string
              adresBuitenland1:
                type: string                
              adresBuitenland2:
                type: string
              adresBuitenland3:
                type: string                    
      burgerservicenummer:
          type: string     
      datumAanvang:
          format: date-time
          type: string            
      datumVoortzetting:
          format: date-time
          type: string             
      datumEinde:
          format: date-time
          type: string   
      inOnderzoek:
          type: boolean
      oefentActiviteitUitIn:
              type: object
              properties:
                vestigingsNummer:
                  type: object
                handelsnamen:
                    type: array
                    description: ''
                    items:
                      type: object
                      properties:
                        handelsnaam:
                          type: string
                          description: ''
                        verkorteNaam:
                          type: string
                          description: ''
                typeringVestiging:
                  type: string
                vestigingsadres:
                    type: array
                    description: ''
                    items:
                      type: object
                      properties:
                        identificatieNummerAanduiding:
                          type: string
                          description: ''
                        postcode:
                          type: string
                          description: ''                    
                        huisnummer:
                          type: string
                          description: ''
                        huisletter:
                          type: string
                          description: ''               
                        huisnummertoevoeging:
                          type: string
                          description: ''
                        locatiebeschrijving:
                          type: string
                          description: ''             
                        naamOpenbareRuimte:
                          type: string
                          description: ''               
                        woonplaatsnaam:
                          type: string
                          description: ''
                        woonplaatsIdentificatie:
                          type: string
                          description: ''          