swagger: '2.0'
info:
  description: Specificatie StUF Json opvragen NNP
  version: 1.0.0
  title: NNP ZoekVestigingOpPostcodeHuisnummer
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /Vestiging/ZoekVestigingOpPostcodeHuisnummer:
    get:
      summary: Opvragen NietNatuurlijkPersoon op ZoekVestigingOpPostcodeHuisnummer
      description: 'Zoek vestiging op Postcode en Huisnummer'
      produces:
        - application/json
      parameters:
        - name: zenderOrganisatie
          in: header
          description: 'Organisatiecode van de opvragende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: zenderApplicatie
          in: header
          description: 'Applicatiecode van de opvragende organisatie'
          required: false
          type: string
        - name: zenderGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: zenderAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens opvraagt'
          required: false
          type: string          
        - name: ontvangerOrganisatie
          in: header
          description: 'Organisatiecode van de leverende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: ontvangerApplicatie
          in: header
          description: 'Applicatiecode van de leverende organisatie'
          required: false
          type: string
        - name: ontvangerGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: ontvangerAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens levert'
          required: false
          type: string        
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Vestiging'
    parameters:
        - name: aoa.postcode
          in: query
          description: 'De door TNT Post vastgestelde code behorende bij een bepaalde combinatie van een naam van een woonplaats, naam van een openbare ruimte en een huisnummer.'
          required: true
          type: string
        - name: aoa.huisnummer
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering.'
          required: true
          type: integer
          format: int32
        - name: aoa.huisletter
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken.'
          required: false
          type: string
        - name: aoa.huisnummertoevoeging
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter.'
          required: false
          type: string
definitions:
  Vestiging:
    type: object
    properties:
      vestigingsnummer:
        type: string
        description: 'Landelijk uniek identificerend administratienummer van een VESTIGING zoals toegewezen door de Kamer van Koophandel (KvK)'
      authentiek:
        type: boolean
        description: 'Aanduiding of het een authentiek gegeven betreft'
      volgorde:
        type: integer
        description: 'Volgorde van handelsnamen'
      handelsnaam:
        $ref: '#/definitions/Handelsnaam'
      handelsnaamVerkort:
        $ref: '#/definitions/Handelsnaam'
      datumAanvang:
        format: date-time
        type: string
        description: 'Datum aanvang'
      datumEinde:
        format: date-time
        type: string
        description: 'Datum einde'
      typeringVestiging:
        enum:
          - Hoofdvestiging
          - Nevenvestiging
        type: string
        description: 'typeringVestiging'
      verblijfsadres:
        type: object
        description: 'Geeft aan het het een locatie adres of een correspondentie adres betreft'
        properties:
          aoaAdres:
            $ref: '#/definitions/AOAobject'
      sub.correspondentieAdres:
        type: object
        description: 'Geeft aan het het een correspondentie adres betreft'
        properties:
          aoaAdres:
            $ref: '#/definitions/AOAobject'
          sub.verblijfBuitenland:
            $ref: '#/definitions/BuitenlandsAdres'
          sub.postadresType:
            type: string
            description: 'Indicatie of het postadres een antwoordnummer (A) of postbus (P) is'
            enum:
              - postbus
              - antwoordnummer
          sub.postadresNummer:
            type: string
            description: 'De postcode van het postadres'
      sub.telefoonnummer:
        type: string
        description: 'Telefoonnummer waaronder het subject in de regel bereikbaar is'
      sub.faxnummer:
        type: string
        description: 'Faxnummer waaronder het subject in de regel bereikbaar is'
      sub.emailadres:
        type: string
        description: 'Elektronisch postadres waaronder het subject in de regel bereikbaar is'
      sub.url:
        type: string
        description: 'Het label of etiket dat aan de specifieke informatiebron, zoals een webpagina, een bestand of een plaatje op internet is toegewezen waar het SUBJECT in de regel op het internet vindbaar is.'
      sub.bankrekening:
        $ref: '#/definitions/Bankrekening'
      sub.kvkNummer:
        type: object
        description: 'Landelijk uniek identificerend administratienummer van een VESTIGING zoals toegewezen door de Kamer van Koophandel (KvK)'
        properties:
          kvkNummer:
            $ref: '#/definitions/MaatschappelijkeActiviteit'
  MaatschappelijkeActiviteit:
    type: object
    description: 'MaatschappelijkeActiviteit'
    properties:
      sub.kvkNummer:
        type: string
        description: 'Landelijk uniek identificerend administratienummer van een VESTIGING zoals toegewezen door de Kamer van Koophandel (KvK)'
      handelsnamen:
        type: array
        description: 'handelsnamen'
        items:
          $ref: '#/definitions/Handelsnaam'
  Handelsnaam:
    type: object
    description: 'Handelsnaam'
    properties:
      handelsnaam:
        type: string
        description: 'De naam waaronder de onderneming handelt'
      verkorteNaam:
        type: string
        description: 'De door de Kamer van Koophandel bepaalde naam van de onderneming ten behoeve van adresseringsdoeleinden'
  AOAobject:
    type: object
    description: 'AOAobject'
    properties:
      wpl.woonplaatsNaam:
        type: string
        description: 'Woonplaatsnaam'
      gor.openbareRuimteNaam:
        type: string
        description: 'Een naam die aan een openbare ruimte is toegekend in een daartoe strekkend formeel gemeentelijk besluit. Een openbare ruimte is een door een bevoegde gemeentelijk orgaan als zodanig aangewezen. Voor Naam openbareruimte mag officiële straatnaam gelezen worden'
      gor.straatnaam:
        type: string
        description: 'De officiële straatnaam zoals in het gemeente bestuur is vastgesteld. De naam wordt zo nodig ingekort conform de specificaties van de BOCO-norm'
      aoa.postcode:
        type: string
        description: 'Postcode'
        minLength: 6
        maxLength: 6
        pattern: 9999NN
      aoa.huisnummer:
        type: integer
        description: 'Huisnummer'
        minimum: 1
      aoa.huisletter:
        type: string
        description: 'Huisletter'
      aoa.huisnummertoevoeging:
        type: string
        description: 'Huisnummertoevoeging'
      aoa.identificatie:
        type: number
        description: 'Het unieke identifiecatienummer van de Adresseerbaar Object Aanduiding'
  BuitenlandsAdres:
    type: object
    description: 'BuitenlandsAdres'
    properties:
      lnd.landnaam:
        type: string
        description: 'Landnaam'
      lnd.landcode:
        type: integer
        description: 'Het LAND waarin het SUBJECT heeft aangegeven te (gaan) verblijven dan wel verblijft. De landcode is gemodeleerd, maar voor die "view" datamodel kan de genwenste waarde hier opgeslagen worden'
      sub.adresBuitenland1:
        type: string
        description: 'Het eerste deel van het adres in het buitenland dat het SUBJECT opgeeft bij vertrek naar het buitenland dan wel waar het SUBJECT in het buitenland verblijft'
      sub.adresBuitenland2:
        type: string
        description: 'Het tweede deel van het adres in het buitenland dat het SUBJECT opgeeft bij vertrek naar het buitenland dan wel waar het SUBJECT in het buitenland verblijft'
      sub.adresBuitenland3:
        type: string
        description: 'Het derde deel van het adres in het buitenland dat het SUBJECT opgeeft bij vertrek naar het buitenland dan wel waar het SUBJECT in het buitenland verblijft'
  Bankrekening:
    type: object
    description: 'Het nummer van een Nederlandse bank/girorekening, zoals dat door een bankinstelling als identificator aan een overeenkomst tussen de bank en een of meer subjecten wordt toegekend, op basis waarvan het SUBJECT in de regel financieel communiceert'
    properties:
      iban:
        type: string
        description: 'Een International Bank Account Number (IBAN) wordt gebruikt om internationale transacties tussen rekeningen en banken gelegen in verschillende landen vlotter te laten verlopen.'
      bic:
        type: string
        description: 'De Business Identifier Code, afgekort BIC, is een code die wordt gebruikt bij grensoverschrijdend betalingsverkeer om een bank te identificeren.'