swagger: '2.0'
info:
  description: Specificatie StUF Json opvragen NNP
  version: 1.0.0
  title: nnp
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/IngeschrevenNietNatuurlijkPersoon/{statutaireNaam}':
    get:
      summary: Opvragen NietNatuurlijkPersoon StatutaireNaam
      description: 'Vraagt ingeschreven NietNatuurlijkPersoon op StatutaireNaam.'
      produces:
        - application/json
      parameters:
        - name: zender
          in: header
          required: false
          type: string
        - name: ontvanger
          in: header
          required: false
          type: string
        - name: parameters
          in: header
          required: false
          type: string
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: crossRefnummer
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string
      responses:
        '200':
          description: Gelukt
          schema:
            type: object
            properties:
              persoon:
                $ref: '#/definitions/NietNatuurlijkPersoon'
    parameters:
      - name: statutaireNaam
        in: path
        required: true
        type: string
  /IngeschrevenNietNatuurlijkPersoon/NietNatuurlijkPersonenOpPostcodeHuisnummer:
    get:
      summary: >-
        Zoek een ingeschreven NietNatuurlijkPersoon op basis van postcode en eventueel
        huisnummer, huisletter, huisnummertoevoeging en aanduidingbijhuisnummer.
      description: 'Vraagt ingeschreven NietNatuurlijkPersoon op Postcode en Huisnummer.'
      consumes: []
      produces:
        - application/json
      parameters:
        - name: postcode
          in: query
          description: 'De door TNT Post vastgestelde code behorende bij een bepaalde combinatie van een naam van een woonplaats, naam van een openbare ruimte en een huisnummer.'
          required: true
          type: string
        - name: huisnummer
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering.'
          required: true
          type: integer
          format: int32
        - name: huisletter
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken.'
          required: false
          type: string
        - name: huisnummertoevoeging
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter.'
          required: false
          type: string
        - name: van
          in: query
          description: 'van'
          required: false
          type: string
        - name: totEnMet
          in: query
          description: 'TotEnMet'
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NietNatuurlijkPersoon'
  /IngeschrevenNietNatuurlijkPersoon/ZoekIngeschrevenNietNatuurlijkPersonenOpBinnenlandsBezoekadres:
    get:
      summary: 'Zoek ingeschreven NietNatuurlijkPersoon op Binnenlands bezoekadres.'
      description: 'Zoek ingeschreven NietNatuurlijkPersoon op Binnenlands bezoekadres.'
      consumes: []
      produces:
        - application/json
      parameters:
        - name: woonplaatsnaam
          in: query
          description: 'Een woonplaats zoals gedefinieerd in de BAG ligt altijd binnen één gemeente. Een aaneengesloten gedeelte van Nederland dat aangeduid wordt met dezelfde woonplaatsnaam maar dat doorsneden wordt door één of meer gemeentegrenzen wordt aldus geregistreerd als meerdere woonplaatsen.'
          required: true
          type: string
        - name: openbareruimtenaam
          in: query
          description: 'Een door het bevoegde gemeentelijke orgaan aan een GEMEENTELIJKE OPENBARE RUIMTE toegekende benaming.'
          required: true
          type: string
        - name: huisnummer
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering.'
          required: true
          type: integer
          format: int32
        - name: huisletter
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken.'
          required: false
          type: string
        - name: huisnummertoevoeging
          in: query
          description: 'Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter.'
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NietNatuurlijkPersoon'
  /IngeschrevenNietNatuurlijkPersoon/RaadpleegIngeschrevenNietNatuurlijkPersoonOpRsin:
    get:
      summary: 'Raadpleeg ingeschreven NietNatuurlijkPersoon op Rsin'
      description: 'Raadpleeg ingeschreven NietNatuurlijkPersoon op Rsin.'
      consumes: []
      produces:
        - application/json
      parameters:
        - name: rsin
          in: query
          description: 'Een in het handelsregister over een NIET-NATUURLIJK PERSOON opgenomen, door de Kamer van Koophandel toegekend, uniek nummer. De attribuutsoort kent onder meer historie omdat het mogelijk is dat de NNP-ID(RSIN) van een ingeschreven niet-natuurlijk persoon wijzigt, met name vanwege ‘ambtelijke’ correcties.'
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NietNatuurlijkPersoon'
  /IngeschrevenNietNatuurlijkPersoon/RaadpleegIngeschrevenNietNatuurlijkPersoonOpKvknummer:
    get:
      summary: 'Raadpleeg ingeschreven NietNatuurlijkPersoon op Kvk nummer.'
      description: 'Raadpleeg ingeschreven NietNatuurlijkPersoon op Kvk nummer.'
      consumes: []
      produces:
        - application/json
      parameters:
        - name: kvknummer
          in: query
          description: 'Landelijk uniek identificerend administratienummer van een MAATSCHAPPELIJKE ACTIVITEIT zoals toegewezen door de Kamer van Koophandel (KvK).'
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/NietNatuurlijkPersoon'
definitions: 
  NietNatuurlijkPersoon:
    type: object
    properties:
      rsin:
        type: string
      indicatieAuthentiek:
        type: boolean
      typering:
        type: string
      statutaireNaam:
        type: string
      rechtsvorm:
        type: string
      statutaireZetel:
        type: string
      datumAanvang:
        format: date-time
        type: string
      datumVoortzetting:
        format: date-time
        type: string
      datumEinde:
        format: date-time
        type: string
      telefoonnummer:
        type: string
      faxnummer:
        type: string
      emailadres:
        type: string
      url:
        type: string
      bezoekAdres:
        type: object
        properties:
          aoaAdres:
            $ref: '#/definitions/AOAobject'
      bankrekening:
        type: object
        properties:
          bankrekening:
            $ref: '#/definitions/Bankrekening'
      kvknummer:
        type: object
        properties:
          kvknummer:
            $ref: '#/definitions/MaatschappelijkeActiviteit'
  MaatschappelijkeActiviteit:
    type: object
    properties:
      oefentActiviteitenUitVoor:
        $ref: '#/definitions/MaatschappelijkeActiviteitRelatie'
  MaatschappelijkeActiviteitRelatie:
    type: object
    properties:
      maatschappelijkeActiviteit:
        $ref: '#/definitions/MaatschappelijkeActiviteitBeperkt'
  MaatschappelijkeActiviteitBeperkt:
    type: object
    properties:
      datumAanvang:
        format: date-time
        type: string
      datumVoortzetting:
        format: date-time
        type: string
      kvkNummer:
        type: string
      handelsnamen:
        type: array
        items:
          $ref: '#/definitions/Handelsnaam'
      datumEinde:
        format: date-time
        type: string
  Handelsnaam:
    type: object
    properties:
      handelsnaam:
        type: string
      verkorteNaam:
        type: string
  AOAobject:
    type: object
    properties:
      aoa.identificatie:
        type: number
      postcode:
        type: string
        minLength: 6
        maxLength: 6
        pattern: 9999NN
      huisnummer:
        type: integer
        minimum: 1
      huisletter:
        type: string
      huisnummertoevoeging:
        type: string
      openbareRuimteNaam:
        type: string
      straatnaam:
        type: string
      wpl.identificatie:
        type: string
      wpl.woonplaatsNaam:
        type: string
      locatiebeschrijving:
          type: string
  Bankrekening:
    type: object
    properties:
      iban:
        type: string
      bic:
        type: string
