swagger: '2.0'
info:
  description: BAG Zoek Openbareruimte op naam
  version: 1.0.0
  title: BAG ZoekOpenbareruimteOpNaam
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ZoekOpenbareruimteOpNaam:
    get:
      summary: 'Zoek Openbareruimte op naam'
      description: 'Zoek Openbareruimte op naam'
      produces:
        - application/json
      parameters:
        - name: zenderOrganisatie
          in: header
          description: 'Organisatiecode van de opvragende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: zenderApplicatie
          in: header
          description: 'Applicatiecode van de opvragende organisatie'
          required: false
          type: string
        - name: zenderGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: zenderAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens opvraagt'
          required: false
          type: string          
        - name: ontvangerOrganisatie
          in: header
          description: 'Organisatiecode van de leverende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: ontvangerApplicatie
          in: header
          description: 'Applicatiecode van de leverende organisatie'
          required: false
          type: string
        - name: ontvangerGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: ontvangerAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens levert'
          required: false
          type: string        
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string     
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Openbareruimte'
    parameters:
        - name: postcode
          in: query
          description: ''
          required: true
          type: string
        - name: huisnummer
          in: query
          description: ''
          required: true
          type: integer
          format: int32
        - name: huisletter
          in: query
          description: ''
          required: false
          type: string
        - name: huisnummertoevoeging
          in: query
          description: ''
          required: false
          type: string
        - name: locatieaanduiding
          in: query
          description: ''
          required: false
          type: string
definitions:
  Openbareruimte:
    type: object
    properties:
      identificatie:
        type: string
      naamOpenbareRuimte:
        type: string