swagger: '2.0'
info:
  description: Raadpleeg buurt op buurtcode wijkcode gemeentecode
  version: 1.0.0
  title: RaadpleegBuurtOpBuurtcodeWijkcodeGemeenteCode
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
 /RaadpleegBuurtOpBuurtcodeWijkcodeGemeenteCode:
    get:
      summary:  Zoek raadpleeg buurt op buurtcode wijkcode gemeentecode
      description: 'Zoek raadpleeg buurt op buurtcode wijkcode gemeentecode'
      produces:
        - application/json
      parameters:
        - name: zenderOrganisatie
          in: header
          description: 'Organisatiecode van de opvragende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: zenderApplicatie
          in: header
          description: 'Applicatiecode van de opvragende organisatie'
          required: false
          type: string
        - name: zenderGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: zenderAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens opvraagt'
          required: false
          type: string          
        - name: ontvangerOrganisatie
          in: header
          description: 'Organisatiecode van de leverende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: ontvangerApplicatie
          in: header
          description: 'Applicatiecode van de leverende organisatie'
          required: false
          type: string
        - name: ontvangerGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: ontvangerAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens levert'
          required: false
          type: string        
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string
      responses:
        '200':
          description: Gelukt
          schema:
            $ref: '#/definitions/Buurt'
    parameters:
      - name: buurtCode
        in: query
        description: 'buurtCode'
        required: true
        type: string
      - name: wijkcode
        in: query
        description: 'wijkCode'
        required: true
        type: string
      - name: gemeenteCode
        in: query
        description: 'gemeenteCode'
        required: true
        type: string        
definitions:
  Buurt:
    type: object
    properties:
      buurtCode:
        type: string
        description: 'BUURTCODE'
      buurtNummer:
        type: string
        description: 'BUURTNUMMER'
      buurtNaam:
        type: string
        description: 'BUURTNAAM'
      buurtType:
        type: string
        description: 'BUURTTYPE'
      buurtGeometrie:
        type: string
        description: 'kan dit weg?'
      parentCode:
        type: string
        description: 'PARENTCODE indien type = subbuurt, subbuurtdeel of blok'
      datumBeginGeldigheidBuurt:
        type: string
        format: date-time
        description: 'EINDDATUM'
      datumEindeGeldigheidBuurt:
        type: string
        format: date-time
        description: 'BEGINDATUM'
      datumCreatie:
        type: string
        format: date-time
        description: 'CREATION'
      datumInvoer:
        type: string
        format: date-time
        description: 'INGANGSDATUM'
      datumAfvoer:
        type: string
        format: date-time
        description: 'AFVOERDATUM'
      woonplaatsCode:
        type: string
        description: 'WOONPLAATSCODE'
      status:
        type: string
        description: 'STATUS'
      indAuthentiek:
        type: string
        description: 'INDAUTHENTIEK'
      indOnderzoek:
        type: boolean
        description: 'INDINONDERZOEK'
      indGeconstateerd:
        type: boolean
        description: 'INDGECONSTATEERD'
      redenOpvoerCode:
        type: number
        description: 'REDENOPVOERCODE'
      redenOpvoerOmschrijving:
        type: string
        description: 'REDENOPVOER OMSCHRIJVING'
      redenAfvoerCode:
        type: number
        description: 'REDENAFVOERCODE'
      redenAfvoerOmschrijving:
        type: string
        description: 'REDENAFVOER OMSCHRIJVING'
      bronCodeOpvoer:
        type: string
        description: 'BRONCODEOPVOER'
      bronCodeAfvoer:
        type: string
        description: 'BRONCODEAFVOER'
      bronID:
        type: string
        description: 'BRON_ID'
      datumOpvoerPlus:
        type: string
        format: date-time
        description: 'DATUMOPVOERPLUS'
      datumAfvoerPlus:
        type: string
        format: date-time
        description: 'DATUMAFVOERPLUS'
      mutatieReden:
        type: string
        description: 'MUTATIEREDEN'
      BAGProces:
        type: string
        description: 'BAGPROCES'
      omschrijving:
        type: string
      document:
        type: object
        properties:
          documentNummer:
            type: string
            description: 'DOCMENTNUMMER'
          documentDatum:
            type: string
            format: date-time
            description: 'DOCUMENTDATUM ..? niet DD_DOCUMENT?'
      documentPlus:
        type: object
        properties:
          documentNummerPlus:
            type: string
            description: 'DOCUMENTNUMMERPLUS'
          documentDatum:
            type: string
            format: date-time
            description: 'DD_DOCUMENTPLUS'
      wijk:
        type: object
        properties:
          wijkCode:
            type: string
          wijkNaam:
            type: string
          wijkGeometrie:
            type: string
          datumBeginGeldigheidWijk:
            type: string
            format: date-time
          datumEindeGeldigheidWijk:
            type: string
            format: date-time
          gemeenteNaam:
            type: string
          gemeenteCode:
            type: string