swagger: '2.0'
info:
  description: BAG Raadpleeg stand plaats nummeraanduiding op standplaatsidentificatie
  version: 1.0.0
  title: BAG RaadpleegStandplaatsNummeraanduidingOpStandplaatsIdentificatie
  contact: {}
host: zaaksysteem.greenvalley.nl
basePath: /bg
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /RaadpleegStandplaatsNummeraanduidingOpStandplaatsIdentificatie:
    get:
      summary: 'Raadpleeg stand plaats nummeraanduiding op standplaatsidentificatie'
      description: 'Raadpleeg stand plaats nummeraanduiding op '
      produces:
        - application/json
      parameters:
        - name: zenderOrganisatie
          in: header
          description: 'Organisatiecode van de opvragende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: zenderApplicatie
          in: header
          description: 'Applicatiecode van de opvragende organisatie'
          required: false
          type: string
        - name: zenderGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: zenderAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens opvraagt'
          required: false
          type: string          
        - name: ontvangerOrganisatie
          in: header
          description: 'Organisatiecode van de leverende organisatie (kan zijn een gemeentecode, RSIN, OIN)'
          required: false
          type: string
        - name: ontvangerApplicatie
          in: header
          description: 'Applicatiecode van de leverende organisatie'
          required: false
          type: string
        - name: ontvangerGebruiker
          in: header
          description: 'Organisatiebrede unieke gebruikerIdentificatie'
          required: false
          type: string
        - name: ontvangerAdministratie
          in: header
          description: 'Administratie of organisatieonderdeel die gegevens levert'
          required: false
          type: string        
        - name: referentienummer
          in: header
          required: false
          type: string
        - name: tijdstipbericht
          in: header
          required: false
          type: string
        - name: entiteittype
          in: header
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Standplaats'
    parameters:
        - name: standplaatsIdentificatie
          in: query
          required: true
          type: string
        - name: inclusiefIngetrokkenStandplaatsen
          in: query
          required: false
          type: boolean
definitions:
  Standplaats:
    type: object
    properties:
      adres:
        type: object
        properties:
          identificatieNummeraanduiding:
            type: string
          postcode:
            type: string
          huisnummer:
            type: integer
          huisletter:
            type: string
          huisnummerToevoeging:
            type: string
          locatiebeschrijving:
            type: string
          naamOpenbareRuimte:
            type: string
          woonplaatsNaam:
            type: string
          woonplaatsIdentificatie:
              type: string
      indicatieGeconstateerdeStandplaats:
        type: string
      standplaatsIdentificatie:
        type: string
      standplaatsStatus:
        type: string
      vlakGeometrie:
        type: object
        properties:
          representatie:
            type: string
      datumBeginGeldigheid:   
        format: date-time
        type: string
      datumEindeGeldigheid:
        format: date-time
        type: string    