swagger: '2.0'
info:
  description: Specificatie StUF Json opvragen medewerker gegevens
  version: 1.0.0
  title: Kernregistratie Medewerker
  contact: {}
host: localhost
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /RaadpleegMedewerkerOpWerknemernummerEnContractnummer:
    get:
      summary: opvragen van medewerkergegevens op basis van werknemer- en/of contractnummer
      description: 'Vraagt de gegevens van een medewerker op.'
      produces:
        - application/json
      responses:
        '200':
          description: Gelukt
          schema:
            type: object
            properties:
              medewerker:
                $ref: '#/definitions/kernregistratie_medewerker'
    parameters:
      - name: werknemernummer
        in: query
        required: false
        type: number
      - name: contractnummer
        in: query
        required: false
        type: number
      - name: Historie
        in: query
        type: string 
        required: false
        enum: 
            - J
            - N
      - name: DATUM_INGANG_GELDIGHEID
        in: query
        required: false
        type: string
  /RaadpleegMedewerkerOpGRID_ID:
    get:
      summary: opvragen van medewerkergegevens op basis van GRID_ID
      description: 'Vraagt de gegevens van een medewerker op.'
      produces:
        - application/json
      responses:
        '200':
          description: Gelukt
          schema:
            type: object
            properties:
              medewerker:
                $ref: '#/definitions/kernregistratie_medewerker'
    parameters:
      - name: GRID_ID
        in: query
        required: true
        type: string
  /ZoekMedewerkersOpAchternaam:
    get:
      summary: opvragen van medewerkergegevens op basis van Aanschrijfnaam
      description: 'Vraagt de gegevens van een medewerker op.'
      produces:
        - application/json
      responses:
        '200':
          description: Gelukt
          schema:
            type: object
            properties:
              medewerker:
                $ref: '#/definitions/kernregistratie_medewerker'
    parameters:
      - name: Aanschrijfnaam
        in: query
        required: true
        type: string
definitions:
 kernregistratie_medewerker:
   type: object
   properties:
      AANSCHRIJFNAAM:
       description: De aanschrijfnaam van de medewerker. De achternaam zoals de medewerker die binnen de organisatie wil hanteren.
       type: string
      AFDELINGNUMMER:
       type: number
       description: De codering van niveau 4 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       minLength: 6
       maxLength: 6
      FUNCTIECODE:
       type: number
       description: De code van de functie zoals vastgelegd binnen P&O.
       minLength: 9
       maxLength: 9
      ROEPNAAM:
       description: De roepnaam zoals de medewerker die binnen de organisatie wil hanteren.
       type: string
      VOORLETTERS:
       description: De voorletters van de medewerker.
       type: string
      VOORVOEGSEL:
       description: De voorvoegsels van de geslachtsnaam van de medewerker.
       type: string
      GESLACHTSNAAM:
       type: string
       description: de geslachtsnaam van de medewerker
      GESLACHTSAANDUIDING:
       description: De aanduiding van het geslacht van de medewerker. 
       type: string 
       enum:
          - M
          - V
      STANDPLAATS:
       description: Het adres van de standplaats.
       type: string
      KAMERNUMMER:
       description: Het kamernummer van de kamer waar de medewerker zijn werkplek heeft.
       type: string 
      CONTRACTNUMMER: 
       description: Het contractnummer dit specifieke dienstverband.
       type: number
       minLength: 1
       maxLength: 3
      GRID_ID:
       description: Het gebruikersaccount van de medewerker voor dit specifieke dienstverband.
       type: string
      WERKNEMERNUMMER:
        type: number
        description: Het unieke nummer waaronder een medewerker is geregistreerd binnen applicatie ADP van afdeling P&O.
        minLength: 1
        maxLength: 38
      EINDDATUM_CONTRACT:
       description: Daadwerkelijke einddatum dienstverband.
       type: string
      EMAILADRES:
       description: Het e-mailadres van de medewerker waarop de medewerker binnen de organisatie bereikt wil worden.
       type: string
      WERK_TELEFOONNUMMER_VAST:
       description: Het vaste telefoonnummer van de medewerker waarop de medewerker binnen de organisatie bereikt wil worden.
       type: string
      WERK_TELEFOONNUMMER_MOBIEL:
       description: Het mobiele telefoonnummer van de medewerker waarop de medewerker binnen de organisatie bereikt wil worden.
       type: string
      INGANGSDATUM_CONTRACT:
       description: Ingangsdatum dienstverband.
       type: string
      EINDDATUM_CONTRACT_BEOOGD:
       description: Geplande einddatum dienstverband.
       type: string
      KLANTNUMMER:
       description: Code van het organisatie onderdeel waar dit dienstverband door betaald wordt.
       type: string
      KLANTOMSCHRIJVING:
       description: Omschrijving van het organisatie onderdeel waar dit dienstverband door betaald wordt.
       type: string
      MOEDERAFDELING:
       description: De codering van niveau 1 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      MOEDER_AFKORTING:
       description: De afkorting van niveau 1 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      MOEDERAFDELING_OMSCHRIJVING:
       description: De omschrijving van de moederafdeling
       type: string
      DIENSTNUMMER:
       description: De codering van niveau 2 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      DIENSTOMSCHRIJVING:
       description: De omschrijving van niveau 2 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      DIENST_AFKORTING:
       description: De afkorting van niveau 2 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      SECTORNUMMER:
       description: De codering van niveau 3 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      SECTOROMSCHRIJVING:
       description: De omschrijving van niveau 3 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      SECTOR_AFKORTING:
       description: De afkorting van niveau 3 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      AFDELINGOMSCHRIJVING:
       description: De omschrijving van niveau 4 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      AFDELING_AFKORTING:
       description: De afkorting van niveau 4 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      BUREAUNUMMER:
       description: De codering van niveau 5 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      BUREAUOMSCHRIJVING:
       description: De omschrijving van niveau 5 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      BUREAU_AFKORTING:
       description: De afkorting van niveau 5 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      UNITNUMMER:
       description: De codering van niveau 6 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      UNITOMSCHRIJVING: 
       description: De omschrijving van niveau 6 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      UNIT_AFKORTING:
       description: De omschrijving van niveau 6 in de te onderscheiden hiërarchie binnen de organisatiestructuur.
       type: string
      ORGANISATIESTRUCTUUR:
       description: Een samenstelling van de afkortingen van de niveaus van organisatorische eenheden, gescheiden door "/".
       type: string
      FUNCTIEOMSCHRIJVING: 
       description: De omschrijving van de functie zoals vastgelegd binnen P&O (globale functieomschrijving)
       type: string
      HISTORIE:
       description: Is de opgevraagde persoon in dienst of is deze uitdienst
       type: string
       enum:
          - J
          - N
      DATUM_INGANG_GELDIGHEID:
       type: string
       description: De datum waarop een record geldig wordt